# ─── sandbox help ─────────────────────────────────────────────────────────────
# Sourced by sandbox.sh — handles: sandbox <action> -h | --help
# Variables inherited: ACTION, logging/color functions
# ─────────────────────────────────────────────────────────────────────────────

case "$ACTION" in
    conn)
        echo ""
        echo -e "  ${CYAN}sandbox conn${NC} — MCP connection manager"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox conn <resource> [parameters]"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}list${NC}     List all saved connections"
        echo -e "    ${CYAN}add${NC}      Add a new saved connection"
        echo -e "    ${CYAN}delete${NC}   Delete a saved connection"
        echo -e "    ${CYAN}rename${NC}   Rename a saved connection"
        echo -e "    ${CYAN}test${NC}     Test a saved connection"
        echo ""
        echo -e "  ${YELLOW}Parameters (add):${NC}"
        echo -e "    ${CYAN}--name${NC}  <name>       Required. Connection name"
        echo -e "    ${CYAN}--user${NC}  <user>       Required. Database user"
        echo -e "    ${CYAN}--pass${NC}  <password>   Optional. Default: env password"
        echo -e "    ${CYAN}--host${NC}  <host>       Optional. Default: env host"
        echo -e "    ${CYAN}--port${NC}  <port>       Optional. Default: env port"
        echo -e "    ${CYAN}--pdb${NC}   <PDB name>   Optional. Default: env service"
        echo ""
        echo -e "  ${YELLOW}Parameters (delete / test):${NC}"
        echo -e "    ${CYAN}--name${NC}  <name>   Required. Connection name"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox conn list"
        echo -e "    sandbox conn add --name sandbox-mcp --user demasy_ai --pdb SANDBOX_PDB"
        echo -e "    sandbox conn rename --from sandbox-mcp --to demasy-mcp"
        echo -e "    sandbox conn test --name sandbox-mcp"
        echo -e "    sandbox conn delete --name sandbox-mcp"
        echo ""
        ;;
    logs)
        echo ""
        echo -e "  ${CYAN}sandbox logs${NC} — View sandbox log files"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox logs <resource> [parameters]"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}apex${NC}      APEX installation logs"
        echo -e "    ${CYAN}install${NC}   All installation logs (APEX + ORDS)"
        echo -e "    ${CYAN}ords${NC}      ORDS runtime log"
        echo -e "    ${CYAN}startup${NC}   Container startup / user-setup log"
        echo -e "    ${CYAN}mcp${NC}       MCP server log"
        echo -e "    ${CYAN}all${NC}       All log files combined"
        echo ""
        echo -e "  ${YELLOW}Parameters:${NC}"
        echo -e "    ${CYAN}-f${NC}, ${CYAN}--follow${NC}        Stream log output (like tail -f)"
        echo -e "    ${CYAN}-n${NC}, ${CYAN}--lines${NC} <N>     Number of lines to show (default: 50)"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox logs startup"
        echo -e "    sandbox logs apex"
        echo -e "    sandbox logs ords --follow"
        echo -e "    sandbox logs install --lines 100"
        echo -e "    sandbox logs all"
        echo ""
        ;;
    status)
        echo ""
        echo -e "  ${CYAN}sandbox status${NC} — Show running status of a service"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox status [resource] [--format json|csv|table]"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}database${NC}  Oracle database — port and SQL connectivity (default: all)"
        echo -e "    ${CYAN}apex${NC}      APEX/ORDS — process, port, HTTP endpoints"
        echo -e "    ${CYAN}mcp${NC}       MCP server — process check"
        echo ""
        echo -e "  ${YELLOW}Parameters:${NC}"
        echo -e "    ${CYAN}--format${NC}  <format>   Output format: json|csv|table (default: table)"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox status                          # Show all (table format)"
        echo -e "    sandbox status database                 # Show database status"
        echo -e "    sandbox status apex"
        echo -e "    sandbox status --format json            # JSON output (all components)"
        echo -e "    sandbox status --format csv             # CSV output"
        echo -e "    sandbox status database --format json   # Database as JSON"
        echo ""
        ;;
    run)
        echo ""
        echo -e "  ${CYAN}sandbox run${NC} — Connect to or run a service"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox run <resource> [parameters]"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}sqlcl${NC}        Open an interactive SQLcl session"
        echo -e "    ${CYAN}mcp${NC}          Run the MCP server"
        echo -e "    ${CYAN}healthcheck${NC}  Run the Oracle sandbox healthcheck"
        echo ""
        echo -e "  ${YELLOW}Parameters (sqlcl):${NC}"
        echo -e "    ${CYAN}-u${NC}, ${CYAN}--user${NC} <user>       Required. Database user to connect as"
        echo -e "    ${CYAN}-p${NC}, ${CYAN}--pass${NC} <password>   Optional. Default: Default Password"
        echo ""
        echo -e "  ${YELLOW}Valid users:${NC}"
        echo -e "    ${CYAN}sys${NC}          SYS (sysdba) — CDB root"
        echo -e "    ${CYAN}system${NC}       SYSTEM — CDB root"
        echo -e "    ${CYAN}sandbox${NC}      SANDBOX — application user (PDB)"
        echo -e "    ${CYAN}sandbox_ai${NC}   SANDBOX_AI — AI/MCP user (PDB)"
        echo -e "    ${CYAN}demasy${NC}       DEMASY — application user (PDB)"
        echo -e "    ${CYAN}demasy_ai${NC}    DEMASY_AI — AI/MCP user (PDB)"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox run sqlcl --user system"
        echo -e "    sandbox run sqlcl --user demasy"
        echo -e "    sandbox run sqlcl -u sandbox"
        echo -e "    sandbox run sqlcl --user demasy --pass mypassword"
        echo -e "    sandbox run healthcheck"
        echo ""
        ;;
    start)
        echo ""
        echo -e "  ${CYAN}sandbox start${NC} — Start a service"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox start <resource> [parameters]"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}apex${NC}         Start Oracle APEX (ORDS)"
        echo -e "    ${CYAN}mcp${NC}          Start the MCP server"
        echo ""
        echo -e "  ${YELLOW}Parameters (mcp):${NC}"
        echo -e "    ${CYAN}-d${NC}, ${CYAN}--default${NC}                       Use the default saved connection"
        echo -e "    ${CYAN}-c${NC}, ${CYAN}--conn${NC} <name>  Use the specified saved connection"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox start apex"
        echo -e "    sandbox start mcp -d"
        echo -e "    sandbox start mcp -c sandbox-mcp-conn"
        echo -e "    sandbox start mcp --conn sandbox-mcp-conn"
        echo -e "    sandbox start mcp --conn demasy-mcp-conn"
        echo ""
        ;;
    stop)
        echo ""
        echo -e "  ${CYAN}sandbox stop${NC} — Stop a running service"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox stop <resource>"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}apex${NC}     Stop Oracle APEX (ORDS)"
        echo -e "    ${CYAN}mcp${NC}      Stop the MCP server"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox stop apex"
        echo ""
        ;;
    restart)
        echo ""
        echo -e "  ${CYAN}sandbox restart${NC} — Restart a service"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox restart <resource>"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}apex${NC}     Restart Oracle APEX (ORDS)"
        echo -e "    ${CYAN}mcp${NC}      Restart the MCP server"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox restart apex"
        echo ""
        ;;
    install)
        echo ""
        echo -e "  ${CYAN}sandbox install${NC} — Install Oracle components"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox install <resource>"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}apex${NC}      Install Oracle APEX + ORDS"
        echo -e "    ${CYAN}schema${NC}    Install Oracle sample schemas (HR, OE, PM, SH)"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox install apex"
        echo -e "    sandbox install schema --name hr"
        echo -e "    sandbox install schema --name oe"
        echo ""
        ;;
    uninstall)
        echo ""
        echo -e "  ${CYAN}sandbox uninstall${NC} — Uninstall Oracle components"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox uninstall <resource>"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}apex${NC}      Uninstall Oracle APEX + ORDS"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox uninstall apex"
        echo ""
        ;;
    download)
        echo ""
        echo -e "  ${CYAN}sandbox download${NC} — Download Oracle components"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox download <resource>"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}apex${NC}   Download Oracle APEX + ORDS"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox download apex"
        echo ""
        ;;
    export)
        echo ""
        echo -e "  ${CYAN}sandbox export${NC} — Export configurations and connections"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox export [resource] [--format json|csv|table]"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}config${NC}       Export all settings (default)"
        echo -e "    ${CYAN}connections${NC}  Export saved database connections only"
        echo -e "    ${CYAN}all${NC}          Export everything (same as config)"
        echo ""
        echo -e "  ${YELLOW}Parameters:${NC}"
        echo -e "    ${CYAN}--format${NC}  <format>   Output format: json|csv|table (default: table)"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox export"
        echo -e "    sandbox export --format json"
        echo -e "    sandbox export connections --format csv"
        echo ""
        ;;
    import)
        echo ""
        echo -e "  ${CYAN}sandbox import${NC} — Import configurations and connections from files"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox import <resource> --file <path> [--format json|csv]"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}config${NC}       Import configuration settings from file"
        echo -e "    ${CYAN}connections${NC}  Import saved database connections from file"
        echo -e "    ${CYAN}all${NC}          Import all resources (future feature)"
        echo ""
        echo -e "  ${YELLOW}Parameters:${NC}"
        echo -e "    ${CYAN}--file${NC}   <path>     Required. Path to import file (.json or .csv)"
        echo -e "    ${CYAN}--format${NC}  <format>   Optional. Auto-detected from file extension"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox import connections --file /tmp/conns.json"
        echo -e "    sandbox import config --file config.csv"
        echo -e "    sandbox import connections --file connections.csv --format csv"
        echo ""
        ;;
    batch)
        echo ""
        echo -e "  ${CYAN}sandbox batch${NC} — Execute batch operations from a file"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox batch <operation> --file <path> [--dry-run] [--rollback]"
        echo ""
        echo -e "  ${YELLOW}Operations:${NC}"
        echo -e "    ${CYAN}apply-connections${NC}    Apply connection additions from CSV file"
        echo -e "    ${CYAN}apply-commands${NC}        Execute sandbox commands from file (one per line)"
        echo -e "    ${CYAN}apply-with-rollback${NC}   Apply operations with automatic rollback on error"
        echo -e "    ${CYAN}execute${NC}               Generic command execution (alias for apply-commands)"
        echo ""
        echo -e "  ${YELLOW}Parameters:${NC}"
        echo -e "    ${CYAN}--file${NC}       <path>   Required. Path to batch file (.csv or .txt)"
        echo -e "    ${CYAN}--dry-run${NC}             Preview operations without applying changes"
        echo -e "    ${CYAN}--rollback${NC}            Enable automatic rollback on error (apply-with-rollback)"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox batch apply-connections --file connections.csv"
        echo -e "    sandbox batch apply-commands --file commands.txt"
        echo -e "    sandbox batch execute --file my_batch.txt --dry-run"
        echo -e "    sandbox batch apply-with-rollback --file connections.csv"
        echo ""
        ;;
    monitor)
        echo ""
        echo -e "  ${CYAN}sandbox monitor${NC} — Real-time monitoring dashboard and metrics export"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox monitor [<resource>] [--export json|prometheus|grafana]"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}system${NC}       System metrics (CPU, memory, disk, uptime)"
        echo -e "    ${CYAN}database${NC}     Database metrics (connections, transactions)"
        echo -e "    ${CYAN}apex${NC}         APEX/ORDS metrics (response time, requests)"
        echo -e "    ${CYAN}all${NC}          Collect all metrics (default)"
        echo ""
        echo -e "  ${YELLOW}Parameters:${NC}"
        echo -e "    ${CYAN}--export${NC}  <format>   Export format: json (Grafana), prometheus, or table (default)"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox monitor"
        echo -e "    sandbox monitor all --export json"
        echo -e "    sandbox monitor database --export prometheus"
        echo -e "    sandbox monitor system --export grafana"
        echo ""
        ;;
    audit)
        echo ""
        echo -e "  ${CYAN}sandbox audit${NC} — Track operations and manage audit logs"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox audit <operation> [--search <criteria>] [--export json|csv] [--limit N]"
        echo ""
        echo -e "  ${YELLOW}Operations:${NC}"
        echo -e "    ${CYAN}list${NC}       Display recent audit log entries (default)"
        echo -e "    ${CYAN}show${NC}       Show detailed entry (requires entry ID)"
        echo -e "    ${CYAN}search${NC}     Search audit logs by criteria"
        echo -e "    ${CYAN}export${NC}     Export audit logs (JSON or CSV)"
        echo -e "    ${CYAN}stats${NC}      Display audit statistics and summary"
        echo -e "    ${CYAN}rollback${NC}   Rollback an operation (requires entry ID)"
        echo ""
        echo -e "  ${YELLOW}Parameters:${NC}"
        echo -e "    ${CYAN}--search${NC}   <criteria>  Search pattern (for search/show operations)"
        echo -e "    ${CYAN}--export${NC}   <format>    Export format: json or csv"
        echo -e "    ${CYAN}--limit${NC}    <N>         Limit results to N entries (default: 50)"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox audit list --limit 20"
        echo -e "    sandbox audit search --search 'install' --export csv"
        echo -e "    sandbox audit show --search 1234567890.12345"
        echo -e "    sandbox audit export --export json"
        echo -e "    sandbox audit stats"
        echo -e "    sandbox audit rollback --search 1234567890.12345"
        echo ""
        ;;
    template)
        echo ""
        echo -e "  ${CYAN}sandbox template${NC} — Save/restore sandbox configuration templates"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox template <operation> [--name <name>] [--description <text>]"
        echo ""
        echo -e "  ${YELLOW}Operations:${NC}"
        echo -e "    ${CYAN}save${NC}       Save current configuration as template"
        echo -e "    ${CYAN}load${NC}       Load template configuration (optionally apply with --apply)"
        echo -e "    ${CYAN}list${NC}       List all available templates"
        echo -e "    ${CYAN}delete${NC}     Delete a template"
        echo -e "    ${CYAN}export${NC}     Export template file (requires --file)"
        echo -e "    ${CYAN}import${NC}     Import template file (requires --file)"
        echo ""
        echo -e "  ${YELLOW}Parameters:${NC}"
        echo -e "    ${CYAN}--name${NC}         <name>         Template name (or use as resource argument)"
        echo -e "    ${CYAN}--description${NC}  <text>         Template description (save operation)"
        echo -e "    ${CYAN}--file${NC}         <path>         File path (export/import operations)"
        echo -e "    ${CYAN}--format${NC}       json|csv       Output format for list (default: table)"
        echo -e "    ${CYAN}--apply${NC}                        Auto-apply configuration when loading"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox template save --name production --description 'Production config'"
        echo -e "    sandbox template load --name production --apply"
        echo -e "    sandbox template list --format json"
        echo -e "    sandbox template export --name production --file /tmp/prod.template"
        echo -e "    sandbox template import --file /tmp/prod.template --name imported"
        echo -e "    sandbox template delete --name production"
        echo ""
        ;;
    backup)
        echo ""
        echo -e "  ${CYAN}sandbox backup${NC} — Backup connections, ORDS config, and Oracle schemas"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox backup <resource>"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}full${NC}          Backup everything"
        echo -e "    ${CYAN}connections${NC}   Backup saved connection files"
        echo -e "    ${CYAN}ords${NC}          Backup ORDS configuration"
        echo -e "    ${CYAN}config${NC}        Backup sandbox environment config"
        echo -e "    ${CYAN}schemas${NC}       Backup Oracle schemas via Data Pump (expdp)"
        echo -e "    ${CYAN}list${NC}          List available backups"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox backup full"
        echo -e "    sandbox backup connections"
        echo -e "    sandbox backup schemas"
        echo -e "    sandbox backup list"
        echo ""
        ;;
    restore)
        echo ""
        echo -e "  ${CYAN}sandbox restore${NC} — Restore from a previous backup"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox restore <resource> [--from <backup-id>]"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}full${NC}          Restore everything"
        echo -e "    ${CYAN}connections${NC}   Restore saved connection files"
        echo -e "    ${CYAN}ords${NC}          Restore ORDS configuration"
        echo -e "    ${CYAN}config${NC}        Restore sandbox environment config"
        echo -e "    ${CYAN}schemas${NC}       Restore Oracle schemas via Data Pump (impdp)"
        echo ""
        echo -e "  ${YELLOW}Parameters:${NC}"
        echo -e "    ${CYAN}--from${NC}  <backup-id>   Backup ID (e.g. 20260626-214354). Default: latest."
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox restore full"
        echo -e "    sandbox restore connections --from 20260626-214354"
        echo -e "    sandbox restore schemas --from 20260626-214354"
        echo ""
        ;;
esac
